# Generated by Django 5.2.8 on 2025-11-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('item_type', models.CharField(choices=[('CURRY', 'Curry'), ('DRINK', 'Drink'), ('POTION', 'Potion')], default='CURRY', max_length=10)),
                ('stats_boost', models.CharField(blank=True, help_text='e.g., Stamina +10', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('reward', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
